{% set name = "r-annotables" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  skip: true  # [not (linux and x86_64)]
  script: $R CMD INSTALL --library="${PREFIX}/lib/R/library" .

requirements:
  host:
    - r-base>=4.2.0
    - r-tibble
  run:
    - r-base>=4.2.0
    - r-tibble

test:
  commands:
    - $R -e "library(annotables); stopifnot(exists('grch38'))"

about:
  home: https://github.com/stephenturner/annotables
  summary: Ensembl annotation tables for R
  license: GPL-3
  license_family: GPL
